# Generated by Django 6.0.2 on 2026-02-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(max_length=50, unique=True, verbose_name="设备ID"),
                ),
                (
                    "device_name",
                    models.CharField(max_length=100, verbose_name="设备名称/断面名称"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[("sensor", "传感器"), ("controller", "控制器")],
                        default="sensor",
                        max_length=20,
                        verbose_name="设备类型",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="设备位置"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="省份"
                    ),
                ),
                (
                    "province_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="省份代码"
                    ),
                ),
                (
                    "river_basin",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="流域"
                    ),
                ),
                (
                    "river_basin_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="流域代码"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("error", "故障"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="设备状态",
                    ),
                ),
                (
                    "last_data_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后数据时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
                "db_table": "devices",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["province_code"], name="devices_provinc_e74364_idx"
                    ),
                    models.Index(
                        fields=["river_basin_code"], name="devices_river_b_f47d5e_idx"
                    ),
                    models.Index(fields=["status"], name="devices_status_9f14cf_idx"),
                    models.Index(
                        fields=["device_type"], name="devices_device__f7aa79_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("temperature", "水温异常"),
                            ("dissolved_oxygen", "溶解氧异常"),
                            ("ph", "pH异常"),
                            ("water_quality", "水质异常"),
                            ("conductivity", "电导率异常"),
                            ("turbidity", "浊度异常"),
                            ("device_offline", "设备离线"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="告警类型",
                    ),
                ),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "警告"),
                            ("critical", "严重"),
                        ],
                        max_length=20,
                        verbose_name="告警级别",
                    ),
                ),
                ("message", models.TextField(verbose_name="告警消息")),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="告警值",
                    ),
                ),
                (
                    "value_unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="值单位"
                    ),
                ),
                ("resolved", models.BooleanField(default=False, verbose_name="已解决")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="告警时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="数据来源"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        db_column="device_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="sensors.device",
                        to_field="device_id",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "告警",
                "verbose_name_plural": "告警",
                "db_table": "alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-created_at"],
                        name="alerts_device__957e7b_idx",
                    ),
                    models.Index(
                        fields=["alert_type"], name="alerts_alert_t_eda531_idx"
                    ),
                    models.Index(
                        fields=["alert_level"], name="alerts_alert_l_98a25e_idx"
                    ),
                    models.Index(fields=["resolved"], name="alerts_resolve_915a53_idx"),
                    models.Index(
                        fields=["created_at"], name="alerts_created_965da5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="水温(℃)",
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="pH值",
                    ),
                ),
                (
                    "dissolved_oxygen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="溶解氧(mg/L)",
                    ),
                ),
                (
                    "conductivity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="电导率(μS/cm)",
                    ),
                ),
                (
                    "turbidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="浊度(NTU)",
                    ),
                ),
                (
                    "salinity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="盐度(‰)",
                    ),
                ),
                (
                    "water_quality",
                    models.CharField(
                        blank=True,
                        help_text="Ⅰ类、Ⅱ类、Ⅲ类、Ⅳ类、Ⅴ类、劣Ⅴ类",
                        max_length=10,
                        null=True,
                        verbose_name="水质类别",
                    ),
                ),
                (
                    "permanganate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="高锰酸盐指数(mg/L)",
                    ),
                ),
                (
                    "ammonia_nitrogen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="氨氮(mg/L)",
                    ),
                ),
                (
                    "total_phosphorus",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="总磷(mg/L)",
                    ),
                ),
                (
                    "total_nitrogen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="总氮(mg/L)",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True,
                        help_text="national/open/simulator/database",
                        max_length=50,
                        null=True,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(db_index=True, verbose_name="监测时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="入库时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        db_column="device_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="sensors.device",
                        to_field="device_id",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "传感器数据",
                "verbose_name_plural": "传感器数据",
                "db_table": "sensor_data",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-recorded_at"],
                        name="sensor_data_device__02ca9a_idx",
                    ),
                    models.Index(
                        fields=["recorded_at"], name="sensor_data_recorde_f507d7_idx"
                    ),
                    models.Index(
                        fields=["data_source"], name="sensor_data_data_so_cfbda9_idx"
                    ),
                    models.Index(
                        fields=["water_quality"], name="sensor_data_water_q_f2c3d6_idx"
                    ),
                ],
            },
        ),
    ]
