# Generated by Django 6.0.2 on 2026-02-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorDataSnapshot",
            fields=[
                ("snapshot_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "device_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="设备ID"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="设备名称"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="位置"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="省份"
                    ),
                ),
                (
                    "river_basin",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="流域"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="水温(°C)",
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="pH值",
                    ),
                ),
                (
                    "dissolved_oxygen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="溶解氧(mg/L)",
                    ),
                ),
                (
                    "conductivity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="电导率(μS/cm)",
                    ),
                ),
                (
                    "turbidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="浊度(NTU)",
                    ),
                ),
                (
                    "salinity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="盐度(‰)",
                    ),
                ),
                (
                    "water_quality",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="水质类别"
                    ),
                ),
                (
                    "permanganate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="高锰酸盐指数(mg/L)",
                    ),
                ),
                (
                    "ammonia_nitrogen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="氨氮(mg/L)",
                    ),
                ),
                (
                    "total_phosphorus",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="总磷(mg/L)",
                    ),
                ),
                (
                    "total_nitrogen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="总氮(mg/L)",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="数据来源"
                    ),
                ),
                (
                    "snapshot_time",
                    models.DateTimeField(db_index=True, verbose_name="快照时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "传感器数据快照",
                "verbose_name_plural": "传感器数据快照",
                "db_table": "sensor_data_snapshot",
                "ordering": ["-snapshot_time"],
                "indexes": [
                    models.Index(
                        fields=["device_id", "-snapshot_time"],
                        name="sensor_data_device__6f464e_idx",
                    ),
                    models.Index(
                        fields=["snapshot_time"], name="sensor_data_snapsho_c558ce_idx"
                    ),
                    models.Index(
                        fields=["data_source"], name="sensor_data_data_so_16ab68_idx"
                    ),
                    models.Index(
                        fields=["device_id", "snapshot_time"],
                        name="sensor_data_device__e1f326_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device_id", "snapshot_time"),
                        name="unique_device_snapshot_time",
                    )
                ],
            },
        ),
    ]
