# Generated by Django 6.0.2 on 2026-02-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="algae_density",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="藻密度(cells/L)",
            ),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="chlorophyll_a",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="叶绿素a(mg/L)",
            ),
        ),
    ]
