# Generated by Django 6.0.2 on 2026-02-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_add_chlorophyll_algae_density'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='device',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='device_id',
            field=models.CharField(db_index=True, max_length=50, verbose_name='设备ID'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备名称/断面名称'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['device_id', '-recorded_at'], name='sensor_data_device_time_idx'),
        ),
        migrations.RemoveField(
            model_name='alert',
            name='device',
        ),
        migrations.AddField(
            model_name='alert',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='设备ID'),
        ),
        migrations.AddField(
            model_name='alert',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备名称/断面名称'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device_id', '-created_at'], name='alerts_device_time_idx'),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
