# Generated by Codex on 2025-02-14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0004_remove_devices"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordatasnapshot",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="城市"),
        ),
    ]
