# Generated by Django 6.0.2 on 2026-02-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0004_remove_devices"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="sensordata",
                    name="location",
                    field=models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="位置"
                    ),
                ),
                migrations.AddField(
                    model_name="sensordata",
                    name="province",
                    field=models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="省份"
                    ),
                ),
                migrations.AddField(
                    model_name="sensordata",
                    name="city",
                    field=models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="城市"
                    ),
                ),
                migrations.AddField(
                    model_name="sensordata",
                    name="river_basin",
                    field=models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="流域"
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name="sensordata",
                    index=models.Index(fields=["province"], name="sensor_data_province_idx"),
                ),
                migrations.AddIndex(
                    model_name="sensordata",
                    index=models.Index(fields=["city"], name="sensor_data_city_idx"),
                ),
                migrations.AddIndex(
                    model_name="sensordata",
                    index=models.Index(fields=["river_basin"], name="sensor_data_river_idx"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManualSensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="设备ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="设备名称/断面名称",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="位置"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="省份"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="城市"
                    ),
                ),
                (
                    "river_basin",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="流域"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="水温(℃)",
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="pH值",
                    ),
                ),
                (
                    "dissolved_oxygen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="溶解氧(mg/L)",
                    ),
                ),
                (
                    "conductivity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="电导率(μS/cm)",
                    ),
                ),
                (
                    "turbidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="浊度(NTU)",
                    ),
                ),
                (
                    "salinity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="盐度(‰)",
                    ),
                ),
                (
                    "water_quality",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="水质类别",
                    ),
                ),
                (
                    "permanganate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="高锰酸盐指数(mg/L)",
                    ),
                ),
                (
                    "ammonia_nitrogen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="氨氮(mg/L)",
                    ),
                ),
                (
                    "total_phosphorus",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="总磷(mg/L)",
                    ),
                ),
                (
                    "total_nitrogen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="总氮(mg/L)",
                    ),
                ),
                (
                    "chlorophyll_a",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="叶绿素a(mg/L)",
                    ),
                ),
                (
                    "algae_density",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="藻密度(cells/L)",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(db_index=True, verbose_name="监测时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="入库时间"),
                ),
            ],
            options={
                "verbose_name": "手动更新数据",
                "verbose_name_plural": "手动更新数据",
                "db_table": "manual_sensor_data",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["device_id", "-recorded_at"],
                        name="manual_data_device_time_idx",
                    ),
                    models.Index(fields=["recorded_at"], name="manual_data_recorded_idx"),
                    models.Index(fields=["water_quality"], name="manual_data_quality_idx"),
                    models.Index(fields=["province"], name="manual_data_province_idx"),
                    models.Index(fields=["city"], name="manual_data_city_idx"),
                    models.Index(fields=["river_basin"], name="manual_data_river_idx"),
                ],
            },
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS sensor_data_snapshot",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS sensor_data_realtime",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
